### ISSUE TITLE
RSNA initial annotation dataset does not match

### ISSUE THREAD

**Issue by IcecreamArtist** [HieuPhan33/MAVL#5]
Hi. thank you for your nice work and code.

i try to download the RSNA dataset to reproduce the results in the paper. however, i found that the current available RSNA 2018 initial annotation dataset presented at the official website does not fully match with the split file paths given in your github repository. besides, the dataset downloaded from the official website is with the directory name "public_project_LxR6zdR2_images_2018-08-20-184248", instead of the directory name given in the split files: "project_x9N20BZa_images_2018-07-20-153330".

there are 19730 images in your train split, but 3292 of them are not presented in the downloaded dataset. 

could you please give me a hint on where to download the correct version of RSNA for your experiments? thank you very much!

**Comment by hieuvmphan** [comment]
Hi @IcecreamArtist,

Thanks for being interested in our work!


Yes, it is not the Initial Annotation, but rather the Pneumonia Challenge, as shown in [Download images from NIH chest x-ray dataset used in the Pneumonia Challenge](https://s3.amazonaws.com/east1.public.rsna.org/AI/2018/pneumonia-challenge-dataset-adjudicated-kaggle_2018.zip).

Let me know if there are remaining issues.
